#ifndef API_ROUTER_HTTP_STATUS_CODE_HPP_H_
#define API_ROUTER_HTTP_STATUS_CODE_HPP_H_

#include <unordered_map>
#include <string>

namespace apirouter {
namespace http {

enum status_code_t {
    CONTINUE    = 100,
    SWITCHING_PROTOCOLS = 101,
    PROCESSING = 102,
    EARLY_HINTS = 103,

    OK = 200,
    CREATED = 201,
    ACCEPTED = 202,
    NON_AUTH_INFO = 203,
    NO_CONTENT = 204,
    RESET_CONTENT = 205,
    PARTIAL_CONTENT = 206,
    MULTI_STATUS = 207,
    ALREADY_REPORTED = 208,
    IM_USED = 226,

    MULTIPLE_CHOICES = 300,
    MOVED_PERMANENTLY = 301,
    FOUND = 302,
    SEE_OTHER = 303,
    NOT_MODIFIED = 304,
    
    TEMPORARY_REDIRECT = 307,
    PERMANENT_REDIRECT = 308,

    BAD_REQUEST = 400,
    UNAUTHORIZED = 401,
    PAYMENT_REQUIRED = 402,
    FORBIDDEN = 403,
    NOT_FOUND = 404,
    METHOD_NOT_ALLOWED = 405,
    NOT_ACCEPTABLE = 406,
    PROXY_AUTH_REQ = 407,
    REQUEST_TIMEOUT = 408,
    CONFLICT = 409,
    GONE = 410,
    LENGTH_REQUIRED = 411,
    PRECONDITION_FAILED = 412,
    CONTENT_TOO_LARGE = 413,
    URI_TOO_LONG = 414,
    UNSUPPORTED_MEDIA_TYPE = 415,
    RANGE_NOT_SATISFIABLE = 416,
    EXPECTATION_FAILED = 417,
    IM_A_TEAPOT = 418,
    MISDIRECTED_REQUEST = 421,
    UNPROCESSABLE_CONTENT = 422,
    LOCKED = 423,
    FAILED_DEPENDENCY = 424,
    TOO_EARLY = 425,
    UPGRADE_REQUIRED = 426,
    PRECONDITION_REQUIRED = 428,
    TOO_MANY_REQUESTS = 429,
    REQ_HEADER_FIELDS_TOO_BIG = 431,
    UNAVAILABLE_FOR_LEGAL_REASONS = 451,

    INTERNAL_SERVER_ERROR = 500,
    NOT_IMPLEMENTED = 501,
    BAD_GATEWAY = 502,
    SERVICE_UNAVAILABLE = 503,
    GATEWAY_TIMEOUT = 504,
    HTTP_VERSION_NOT_SUPPORTED = 505,
    VARIANT_ALSO_NEGOTIATES = 506,
    INSUFFICIENT_STORAGE = 507,
    LOOP_DETECTED = 508,
    NOT_EXTENDED = 510,
    NETWORK_AUTH_REQUIRED = 511
    
};

static const std::unordered_map<
    status_code_t, std::string
> g_status_code_map =
{
    { CONTINUE, "CONTINUE" },
    { SWITCHING_PROTOCOLS, "SWITCHING PROTOCOLS" },
    { PROCESSING, "PROCESSING" },
    { EARLY_HINTS, "EARLY HINTS" },

    { OK, "OK" },
    { CREATED, "CREATED" },
    { ACCEPTED, "ACCEPTED" },
    { NON_AUTH_INFO, "NON-AUTHORITATIVE INFORMATION" },
    { NO_CONTENT, "NO CONTENT" },
    { RESET_CONTENT, "RESET CONTENT" },
    { PARTIAL_CONTENT, "PARTIAL CONTENT" },
    { MULTI_STATUS, "MULTI-STATUS" },
    { ALREADY_REPORTED, "ALREADY REPORTED" },
    { IM_USED, "IM USED" },

    { MULTIPLE_CHOICES, "MULTIPLE CHOICES" },
    { MOVED_PERMANENTLY, "MOVED PERMANENTLY" },
    { FOUND, "FOUND" },
    { SEE_OTHER, "SEE OTHER" },
    { NOT_MODIFIED, "NOT MODIFIED" },
    { TEMPORARY_REDIRECT, "TEMPORARY REDIRECT" },
    { PERMANENT_REDIRECT, "PERMANENT REDIRECT" },

    { BAD_REQUEST, "BAD REQUEST" },
    { UNAUTHORIZED, "UNAUTHORIZED" },
    { PAYMENT_REQUIRED, "PAYMENT REQUIRED" },
    { FORBIDDEN, "FORBIDDEN" },
    { NOT_FOUND, "NOT FOUND" },
    { METHOD_NOT_ALLOWED, "METHOD NOT ALLOWED" },
    { NOT_ACCEPTABLE, "NOT ACCEPTABLE" },
    { PROXY_AUTH_REQ, "PROXY AUTHENTICATION REQUIRED" },
    { REQUEST_TIMEOUT, "REQUEST TIMEOUT" },
    { CONFLICT, "CONFLICT" },
    { GONE, "GONE" },
    { LENGTH_REQUIRED, "LENGTH REQUIRED" },
    { PRECONDITION_FAILED, "PRECONDITION FAILED" },
    { CONTENT_TOO_LARGE, "CONTENT TOO LARGE" },
    { URI_TOO_LONG, "URI TOO LONG" },
    { UNSUPPORTED_MEDIA_TYPE, "UNSUPPORTED MEDIA TYPE" },
    { RANGE_NOT_SATISFIABLE, "RANGE NOT SATISFIABLE" },
    { EXPECTATION_FAILED, "EXPECTATION FAILED" },
    { IM_A_TEAPOT, "I'M A TEAPOT" },
    { MISDIRECTED_REQUEST, "MISDIRECTED REQUEST" },
    { UNPROCESSABLE_CONTENT, "UNPROCESSABLE CONTENT" },
    { LOCKED, "LOCKED" },
    { FAILED_DEPENDENCY, "FAILED DEPENDENCY" },
    { TOO_EARLY, "TOO EARLY" },
    { UPGRADE_REQUIRED, "UPGRADE REQUIRED" },
    { PRECONDITION_REQUIRED, "PRECONDITION REQUIRED" },
    { TOO_MANY_REQUESTS, "TOO MANY REQUESTS" },
    { REQ_HEADER_FIELDS_TOO_BIG, "REQUEST HEADER FIELDS TOO LARGE" },
    { UNAVAILABLE_FOR_LEGAL_REASONS, "UNAVAILABLE FOR LEGAL REASONS" },

    { INTERNAL_SERVER_ERROR, "INTERNAL SERVER ERROR" },
    { NOT_IMPLEMENTED, "NOT IMPLEMENTED" },
    { BAD_GATEWAY, "BAD GATEWAY" },
    { SERVICE_UNAVAILABLE, "SERVICE UNAVAILABLE" },
    { GATEWAY_TIMEOUT, "GATEWAY TIMEOUT" },
    { HTTP_VERSION_NOT_SUPPORTED, "HTTP VERSION NOT SUPPORTED" },
    { VARIANT_ALSO_NEGOTIATES, "VARIANT ALSO NEGOTIATES" },
    { INSUFFICIENT_STORAGE, "INSUFFICIENT STORAGE" },
    { LOOP_DETECTED, "LOOP DETECTED" },
    { NOT_EXTENDED, "NOT EXTENDED" },
    { NETWORK_AUTH_REQUIRED, "NETWORK AUTHENTICATION REQUIRED" }
};

} // http
} // apirouter


#endif // API_ROUTER_HTTP_STATUS_CODE_HPP_H_